### ISSUE TITLE
Restructure landing page

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/eiffel-community.github.io#8]
### Description
The landing page is not crisp enough to help visitors get a grip on Eiffel quickly. We should take the graphical design from Eiffel repos on Github. Also, we should add some interesting pictures to sharpen the message.
- What is Eiffel? with read more links to history etc.
- Getting started
- Contact info link
- Remove details about eco system repos available except some main repos maybe.
- Remove repo status

### Motivation
Easier to get a grip on what Eiffel is and how to try it out

### Exemplification
-

### Benefits
See Motivation

### Possible Drawbacks
-

**Comment by e-pettersson-ericsson** [comment]
I think the logo used on https://github.com/eiffel-community can be re used also on eiffel-community.github.io
Instead of using pastel colors on the landing page, which is only used there, we keep the same look and feel as the GitHub repositories, with the red, black, grey and white theme used in the Eiffel logo.
